location ^~ /v1 {
    if ($request_method = 'OPTIONS' ) {
        add_header 'Access-Control-Allow-Origin' 'https://appassets.androidplatform.net' always; 
        add_header 'Access-Control-Allow-Credentials' 'true' always; 
        add_header 'Access-Control-Allow-Methods' 'POST' always; 
        add_header 'Access-Control-Allow-Headers' 'authorization,content-type' always; 
        add_header 'Vary' 'origin, access-control-request-method, access-control-request-headers' always; 
        add_header 'Allow' 'POST' always; 
        return 204; 
    }
    proxy_pass https://gateway.ai.cloudflare.com/v1/xxx/default/compat; 
    proxy_set_header Host gateway.ai.cloudflare.com; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header cf-aig-authorization $http_authorization; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection $http_connection; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_set_header X-Forwarded-Port $server_port; 
    proxy_hide_header authorization; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    proxy_ssl_server_name on; 
    proxy_ssl_name $proxy_host; 
    add_header 'Access-Control-Allow-Origin' 'https://appassets.androidplatform.net' always; 
    add_header 'Access-Control-Allow-Credentials' 'true' always; 
    add_header Alt-Svc 'h3=":443"; ma=2592000'; 
    add_header Strict-Transport-Security "max-age=31536000"; 
}
